import { VISA_STATUS_VALUES } from "./selectOptions";

export const EDUCATION_REQUIRED_VISA = [
  VISA_STATUS_VALUES.F1CPT,
  VISA_STATUS_VALUES.F1OPT,
];

export const EAD_NOT_REQUIRED_VISA = [
  VISA_STATUS_VALUES.H1B,
  VISA_STATUS_VALUES.US_CITIZEN,
];

export const EAD_OPTIONAL_VISA = [
  VISA_STATUS_VALUES.L2,
  VISA_STATUS_VALUES.J1,
  VISA_STATUS_VALUES.OTHERS,
];

export const HOME_ADDRESS_CONTACT_NOT_REQUIRED_VISA = [
  VISA_STATUS_VALUES.GREEN_CARD,
  VISA_STATUS_VALUES.US_CITIZEN,
  VISA_STATUS_VALUES.EB1,
  VISA_STATUS_VALUES.EB2,
  VISA_STATUS_VALUES.EB3,
];

export const HOME_ADDRESS_CONTACT_OPTIONAL_VISA = [VISA_STATUS_VALUES.OTHERS];

export const PORT_OF_ENTRY_NOT_REQUIRED_VISA = [VISA_STATUS_VALUES.US_CITIZEN];

export const PORT_OF_ENTRY_OPTIONAL_VISA = [VISA_STATUS_VALUES.OTHERS];

export const US_STAY_ADDRESSES_OPTIONAL_VISA = [
  VISA_STATUS_VALUES.GREEN_CARD,
  VISA_STATUS_VALUES.US_CITIZEN,
  VISA_STATUS_VALUES.OTHERS,
];
