import { VISA_STATUS_VALUES } from "./selectOptions";

export const SEVIS_DSO_VISA_STATUSES = [
  VISA_STATUS_VALUES.F1,
  VISA_STATUS_VALUES.F1CPT,
  VISA_STATUS_VALUES.F1OPT,
  VISA_STATUS_VALUES.F1STEMOPT,
];

export const EAD_VISA_STATUSES = [
  VISA_STATUS_VALUES.F1,
  VISA_STATUS_VALUES.F1CPT,
  VISA_STATUS_VALUES.F1OPT,
  VISA_STATUS_VALUES.F1STEMOPT,
];

export const INDIAN_ADDRESS_VISA_STATUSES = [
  VISA_STATUS_VALUES.F1,
  VISA_STATUS_VALUES.F1CPT,
  VISA_STATUS_VALUES.F1OPT,
  VISA_STATUS_VALUES.F1STEMOPT,
  VISA_STATUS_VALUES.H1B,
];
