export const VISA_STATUS_VALUES = {
  ASYLUM_REFUGEE: "Asylum-Refugee",
  E1: "E-1",
  E2: "E-2",
  E3: "E-3",
  EAD: "EAD",
  EB1: "EB-1",
  EB2: "EB-2",
  EB3: "EB-3",
  F1CPT: "F-1-CPT",
  F1OPT: "F-1-OPT",
  F1STEMOPT: "F-1-STEM-OPT",
  GREEN_CARD: "GreenCard",
  H1B: "H-1B",
  H4: "H-4",
  J1: "J-1",
  J2: "J-2",
  L1: "L-1",
  L2: "L-2",
  OTHERS: "others",
  TN: "TN",
  US_CITIZEN: "USCitizen",
};

export const OPTIONS = {
  ONBOARDING_STATUS: [
    { value: "", label: "" },
    { value: "yetToStart", label: "Yet To Start" },
    { value: "inProgress", label: "In Progress" },
    { value: "completed", label: "Completed" },
  ],
  GENDER: [
    { value: "male", label: "Male" },
    { value: "female", label: "Female" },
    { value: "other", label: "Other" },
  ],
  MARITAL_STATUS: [
    { value: "", label: "Select marital status" },
    { value: "single", label: "Single" },
    { value: "married", label: "Married" },
    { value: "divorced", label: "Divorced" },
    { value: "widowed", label: "Widowed" },
  ],
  VISA_STATUS: [
    { value: "", label: "Select Visa Status" },
    {
      value: VISA_STATUS_VALUES.ASYLUM_REFUGEE,
      label: "Asylum/Refugee (Granted Protection in the U.S.)",
    },
    {
      value: VISA_STATUS_VALUES.E1,
      label: "E-1 (Treaty Trader)",
    },
    {
      value: VISA_STATUS_VALUES.E2,
      label: "E-2 (Treaty Investor)",
    },
    {
      value: VISA_STATUS_VALUES.E3,
      label: "E-3 (Specialty Occupation Professionals from Australia)",
    },
    {
      value: VISA_STATUS_VALUES.EAD,
      label: "EAD (Employment Authorization Document)",
    },
    {
      value: VISA_STATUS_VALUES.EB1,
      label: "EB-1 (Employment-based Permanent Residency - Priority Workers)",
    },
    {
      value: VISA_STATUS_VALUES.EB2,
      label:
        "EB-2 (Employment-based Permanent Residency - Advanced Degree Professionals)",
    },
    {
      value: VISA_STATUS_VALUES.EB3,
      label:
        "EB-3 (Employment-based Permanent Residency - Skilled Workers, Professionals)",
    },
    {
      value: VISA_STATUS_VALUES.F1CPT,
      label: "F1-CPT (Curricular Practical Training for F-1 Students)",
    },
    {
      value: VISA_STATUS_VALUES.F1OPT,
      label: "F1-OPT (Optional Practical Training for F-1 Students)",
    },
    {
      value: VISA_STATUS_VALUES.F1STEMOPT,
      label:
        "F1-STEM-OPT (Science, Technology, Engineering, and Math Extension)",
    },
    {
      value: VISA_STATUS_VALUES.GREEN_CARD,
      label: "Green Card (Lawful Permanent Resident)",
    },
    {
      value: VISA_STATUS_VALUES.H1B,
      label: "H-1B (Specialty Occupations - Engineers, IT Professionals, etc.)",
    },
    {
      value: VISA_STATUS_VALUES.H4,
      label: "H-4 (Dependent of H-1B Holder)",
    },
    {
      value: VISA_STATUS_VALUES.J1,
      label: "J-1 (Exchange Visitor - Interns, Trainees, Scholars, etc.)",
    },
    {
      value: VISA_STATUS_VALUES.J2,
      label: "J-2 (Dependent of J-1 Holder)",
    },
    {
      value: VISA_STATUS_VALUES.L1,
      label: "L-1 (Intracompany Transferee - Managers and Executives)",
    },
    {
      value: VISA_STATUS_VALUES.L2,
      label: "L-2 (Dependent of L-1 Holder)",
    },
    {
      value: VISA_STATUS_VALUES.TN,
      label: "TN (NAFTA Professionals - Canada & Mexico)",
    },
    { value: VISA_STATUS_VALUES.US_CITIZEN, label: "U.S. Citizen" },
    { value: VISA_STATUS_VALUES.OTHERS, label: "Other Visa Types" },
  ],
  PHOTO_ID_TYPE: [
    { value: "", label: "Select Photo ID Type" },
    { value: "DL", label: "Driver's License" },
    { value: "StateID", label: "State ID" },
  ],
  COUNTRY: [
    { value: "", label: "Select country" },
    { value: "india", label: "India" },
    { value: "usa", label: "USA" },
  ],
  STATE_INDIA: [
    { value: "", label: "Select state" },
    { value: "AP", label: "Andhra Pradesh" },
    { value: "AR", label: "Arunachal Pradesh" },
    { value: "AS", label: "Assam" },
    { value: "BR", label: "Bihar" },
    { value: "CT", label: "Chhattisgarh" },
    { value: "GA", label: "Goa" },
    { value: "GJ", label: "Gujarat" },
    { value: "HR", label: "Haryana" },
    { value: "HP", label: "Himachal Pradesh" },
    { value: "JH", label: "Jharkhand" },
    { value: "KA", label: "Karnataka" },
    { value: "KL", label: "Kerala" },
    { value: "MP", label: "Madhya Pradesh" },
    { value: "MH", label: "Maharashtra" },
    { value: "MN", label: "Manipur" },
    { value: "ML", label: "Meghalaya" },
    { value: "MZ", label: "Mizoram" },
    { value: "NL", label: "Nagaland" },
    { value: "OR", label: "Odisha" },
    { value: "PB", label: "Punjab" },
    { value: "RJ", label: "Rajasthan" },
    { value: "SK", label: "Sikkim" },
    { value: "TN", label: "Tamil Nadu" },
    { value: "TG", label: "Telangana" },
    { value: "TR", label: "Tripura" },
    { value: "UP", label: "Uttar Pradesh" },
    { value: "UK", label: "Uttarakhand" },
    { value: "WB", label: "West Bengal" },
  ],
  STATE_USA: [
    { value: "", label: "Select state" },
    { value: "AL", label: "Alabama" },
    { value: "AK", label: "Alaska" },
    { value: "AZ", label: "Arizona" },
    { value: "AR", label: "Arkansas" },
    { value: "CA", label: "California" },
    { value: "CO", label: "Colorado" },
    { value: "CT", label: "Connecticut" },
    { value: "DE", label: "Delaware" },
    { value: "FL", label: "Florida" },
    { value: "GA", label: "Georgia" },
    { value: "HI", label: "Hawaii" },
    { value: "ID", label: "Idaho" },
    { value: "IL", label: "Illinois" },
    { value: "IN", label: "Indiana" },
    { value: "IA", label: "Iowa" },
    { value: "KS", label: "Kansas" },
    { value: "KY", label: "Kentucky" },
    { value: "LA", label: "Louisiana" },
    { value: "ME", label: "Maine" },
    { value: "MD", label: "Maryland" },
    { value: "MA", label: "Massachusetts" },
    { value: "MI", label: "Michigan" },
    { value: "MN", label: "Minnesota" },
    { value: "MS", label: "Mississippi" },
    { value: "MO", label: "Missouri" },
    { value: "MT", label: "Montana" },
    { value: "NE", label: "Nebraska" },
    { value: "NV", label: "Nevada" },
    { value: "NH", label: "New Hampshire" },
    { value: "NJ", label: "New Jersey" },
    { value: "NM", label: "New Mexico" },
    { value: "NY", label: "New York" },
    { value: "NC", label: "North Carolina" },
    { value: "ND", label: "North Dakota" },
    { value: "OH", label: "Ohio" },
    { value: "OK", label: "Oklahoma" },
    { value: "OR", label: "Oregon" },
    { value: "PA", label: "Pennsylvania" },
    { value: "RI", label: "Rhode Island" },
    { value: "SC", label: "South Carolina" },
    { value: "SD", label: "South Dakota" },
    { value: "TN", label: "Tennessee" },
    { value: "TX", label: "Texas" },
    { value: "UT", label: "Utah" },
    { value: "VT", label: "Vermont" },
    { value: "VA", label: "Virginia" },
    { value: "WA", label: "Washington" },
    { value: "WV", label: "West Virginia" },
    { value: "WI", label: "Wisconsin" },
    { value: "WY", label: "Wyoming" },
  ],
  HOW_SOON_RELOCATION: [
    { value: "", label: "Select duration" },
    { value: "withinTwoWeeks", label: "Within 2 weeks" },
    { value: "moreThanTwoWeeks", label: "More than 2 weeks" },
  ],
  STAY_PREFERENCE: [
    { value: "", label: "Select stay preference" },
    { value: "guesthouse", label: "Opt for guest house" },
    { value: "other", label: "Other" },
  ],
  EXPERIENCE_MONTHS: [
    { value: "", label: "Select months" },
    ...Array.from({ length: 12 }, (_, i) => ({
      value: `${i}`,
      label: `${i}`,
    })),
  ],
  OFFER_LETTER_STATUS: [
    { value: "", label: "" },
    { value: "inProgress", label: "In Progress" },
    { value: "accepted", label: "Accepted" },
    { value: "rejected", label: "Rejected" },
  ],
};
