export const data = [
  {
    id: 1,
    name: "KUNCHE",
    phone_numbers: "732 654 9771",
    email: "suneethkunche2608@gmail.com",
    location: "",
    region: "",
    linkedin: "",
    skills:
      "nlp,elasticsearch,tableau,llm,sas,sql,data science,power bi,machine learning,python,tensorflow,python,docker,java,graphql,sql,css,js,kubernetes,agile methodologies,typescript,aws,oracle,git,xml,scrum,html,agile,ui design,jenkins,jira,figma,terraform,rabbitmq,redis,node.js,nosql,github,python,docker,java,graphql,sql,css,js,kubernetes,agile methodologies,typescript,aws,oracle,git,xml,scrum,html,agile,ui design,jenkins,jira,figma,terraform,rabbitmq,redis,node.js,nosql,github,python,docker,java,graphql,sql,css,js,kubernetes,agile methodologies,typescript,aws,oracle,git,xml,scrum,html,agile,ui design,jenkins,jira,figma,terraform,rabbitmq,redis,node.js,nosql,github,python,docker,java,graphql,sql,css,js,kubernetes,agile methodologies,typescript,aws,oracle,git,xml,scrum,html,agile,ui design,jenkins,jira,figma,terraform,rabbitmq,redis,node.js,nosql,github,python,docker,java,graphql,sql,css,js,kubernetes,agile methodologies,typescript,aws,oracle,git,xml,scrum,html,agile,ui design,jenkins,jira,figma,terraform,rabbitmq,redis,node.js,nosql,github",
    total_experience: 39,
    file_path: "",
  },
  {
    id: 2,
    name: "Deepya Paramata",
    phone_numbers: "732 997 5054",
    email: "deepyaparamata@temple.edu",
    location: "",
    region: "",
    linkedin: "",
    skills: "azure,html,tableau,css,python",
    total_experience: 0,
    file_path: "",
  },
  {
    id: 3,
    name: "EDUCATION",
    phone_numbers: "475 307 1622",
    email: "kaveriponugoti2001@gmail.com",
    location: "",
    region: "",
    linkedin: "",
    skills:
      "computer vision,c,html,aws,c++,css,data science,kubernetes,java,python",
    total_experience: 0,
    file_path: "",
  },
  {
    id: 4,
    name: "Triveni Remany",
    phone_numbers: "425 394 9555",
    email: "",
    location: "",
    region: "",
    linkedin: "www.linkedin.com/in/triveni-remany",
    skills: "agile,xml,waterfall,adobe",
    total_experience: 6,
    file_path: "",
  },
  {
    id: 5,
    name: "Thirumalesh Pathuri",
    phone_numbers: " 551  358 8497",
    email: "thirumaleshpathuri1429@gmail.com",
    location: "",
    region: "",
    linkedin: "",
    skills:
      "springboot,node.js,redis,c,git,docker,elasticsearch,github,jenkins,aws,agile,flask,c++,agile methodologies,typescript,kubernetes,java,python",
    total_experience: 3,
    file_path: "",
  },
  {
    id: 6,
    name: "EDUCATION",
    phone_numbers: "",
    email: "ukuru1017@gmail.com",
    location: "",
    region: "",
    linkedin: "",
    skills: "computer vision,html,aws,css,data science,java,python",
    total_experience: 3,
    file_path: "",
  },
  {
    id: 7,
    name: "EDUCATION",
    phone_numbers: "551 260 1867",
    email: "ukuru1017@gmail.com",
    location: "",
    region: "",
    linkedin: "www.linkedin.com/in/udaykumar-k-u1017",
    skills: "computer vision,html,aws,css,data science,java,python",
    total_experience: 3,
    file_path: "",
  },
  {
    id: 8,
    name: "Rohini N",
    phone_numbers: " 1  929  346 2492",
    email: "nrohini891@gmail.com",
    location: "",
    region: "",
    linkedin: "",
    skills:
      "azure,git,node.js,kubernetes,devops,jira,docker,jenkins,agile,terraform,google cloud platform,sql,agile methodologies,python,oracle,compliance,elasticsearch,aws,php,nosql,xml,github,java",
    total_experience: 11,
    file_path: "",
  },
  {
    id: 9,
    name: "SRINIVAS E",
    phone_numbers: "",
    email: "",
    location: "",
    region: "",
    linkedin: "",
    skills: "c,html,adobe,agile,php,sas,c++,css,figma,xml,java,scrum,python",
    total_experience: 23,
    file_path: "",
  },
  {
    id: 10,
    name: "Dharma M",
    phone_numbers: "",
    email: "dharmamakkena06@gmail.com",
    location: "",
    region: "",
    linkedin: "",
    skills:
      "azure,git,node.js,kubernetes,devops,jira,docker,jenkins,terraform,google cloud platform,sql,python,c,aws,iot,swift,php,github,java",
    total_experience: 0,
    file_path: "",
  },
  {
    id: 11,
    name: "Dharma M",
    phone_numbers: "",
    email: "dharmamakkena06@gmail.com",
    location: "",
    region: "",
    linkedin: "",
    skills:
      "azure,git,node.js,kubernetes,devops,jira,docker,jenkins,terraform,google cloud platform,sql,python,c,aws,iot,swift,php,github,java",
    total_experience: 0,
    file_path: "",
  },
  {
    id: 12,
    name: "JORDAN SMITH",
    phone_numbers: "",
    email: "help@enhancv.com",
    location: "",
    region: "",
    linkedin: "",
    skills: "cybersecurity,iot",
    total_experience: 0,
    file_path: "",
  },
  {
    id: 13,
    name: "RAJESH K",
    phone_numbers: "",
    email: "",
    location: "",
    region: "",
    linkedin: "",
    skills:
      "terraform,aws,scrum,css,agile methodologies,sql,agile,jira,js,nosql,jenkins,kubernetes,ui design,html,git,xml,rabbitmq,typescript,redis,python,java,figma,docker,graphql,node.js,github,oracle",
    total_experience: 0,
    file_path: "",
  },
  {
    id: 14,
    name: "KUNCHE",
    phone_numbers: "732 654 9771",
    email: "suneethkunche2608@gmail.com",
    location: "",
    region: "",
    linkedin: "",
    skills:
      "elasticsearch,python,tableau,power bi,llm,sas,tensorflow,machine learning,data science,nlp,sql",
    total_experience: 2,
    file_path: "",
  },
  {
    id: 15,
    name: "KUNCHE",
    phone_numbers: "732 654 9771",
    email: "suneethkunche2608@gmail.com",
    location: "",
    region: "",
    linkedin: "",
    skills:
      "elasticsearch,python,tableau,power bi,llm,sas,tensorflow,machine learning,data science,nlp,sql",
    total_experience: 2,
    file_path: "",
  },
  {
    id: 16,
    name: "KUNCHE",
    phone_numbers: "732 654 9771",
    email: "suneethkunche2608@gmail.com",
    location: "",
    region: "",
    linkedin: "",
    skills:
      "sas,power bi,elasticsearch,sql,tensorflow,python,machine learning,data science,tableau,llm,nlp",
    total_experience: 2,
    file_path: "",
  },
  {
    id: 17,
    name: "RAJESH K",
    phone_numbers: "",
    email: "",
    location: "",
    region: "",
    linkedin: "",
    skills:
      "python,docker,java,graphql,sql,css,js,kubernetes,agile methodologies,typescript,aws,oracle,git,xml,scrum,html,agile,ui design,jenkins,jira,figma,terraform,rabbitmq,redis,node.js,nosql,github",
    total_experience: 0,
    file_path: "",
  },
  {
    id: 18,
    name: "Triveni Remany",
    phone_numbers: "425 394 9555",
    email: "",
    location: "",
    region: "",
    linkedin: "www.linkedin.com/in/triveni-remany",
    skills: "waterfall,xml,agile,adobe",
    total_experience: 6,
    file_path: "",
  },
  {
    id: 19,
    name: "Sateesh",
    phone_numbers: "646 690 4988",
    email: "",
    location: "",
    region: "",
    linkedin: "",
    skills: "agile,c++,java,azure,git,sql,css,xml,scrum,c,html",
    total_experience: 10,
    file_path: "",
  },
  {
    id: 20,
    name: "Uday Kumar",
    phone_numbers: "",
    email: "",
    location: "",
    region: "",
    linkedin: "",
    skills:
      "agile,python,aws,java,jenkins,azure,penetration testing,c,compliance,devops,sql,css,xml,terraform,html",
    total_experience: 10,
    file_path: "",
  },
  {
    id: 21,
    name: "RAJESH K",
    phone_numbers: "",
    email: "",
    location: "",
    region: "",
    linkedin: "",
    skills:
      "python,docker,java,graphql,sql,css,js,kubernetes,agile methodologies,typescript,aws,oracle,git,xml,scrum,html,agile,ui design,jenkins,jira,figma,terraform,rabbitmq,redis,node.js,nosql,github",
    total_experience: 0,
    file_path: "",
  },
  {
    id: 22,
    name: "RAJESH K",
    phone_numbers: "",
    email: "",
    location: "",
    region: "",
    linkedin: "",
    skills:
      "python,docker,java,graphql,sql,css,js,kubernetes,agile methodologies,typescript,aws,oracle,git,xml,scrum,html,agile,ui design,jenkins,jira,figma,terraform,rabbitmq,redis,node.js,nosql,github",
    total_experience: 0,
    file_path: "",
  },
  {
    id: 23,
    name: "RAJESH K",
    phone_numbers: "",
    email: "",
    location: "",
    region: "",
    linkedin: "",
    skills:
      "python,docker,java,graphql,sql,css,js,kubernetes,agile methodologies,typescript,aws,oracle,git,xml,scrum,html,agile,ui design,jenkins,jira,figma,terraform,rabbitmq,redis,node.js,nosql,github",
    total_experience: 0,
    file_path: "",
  },
  {
    id: 24,
    name: "RAJESH K",
    phone_numbers: "",
    email: "",
    location: "",
    region: "",
    linkedin: "",
    skills:
      "python,docker,java,graphql,sql,css,js,kubernetes,agile methodologies,typescript,aws,oracle,git,xml,scrum,html,agile,ui design,jenkins,jira,figma,terraform,rabbitmq,redis,node.js,nosql,github",
    total_experience: 0,
    file_path: "",
  },
  {
    id: 25,
    name: "RAJESH K",
    phone_numbers: "",
    email: "",
    location: "",
    region: "",
    linkedin: "",
    skills:
      "python,docker,java,graphql,sql,css,js,kubernetes,agile methodologies,typescript,aws,oracle,git,xml,scrum,html,agile,ui design,jenkins,jira,figma,terraform,rabbitmq,redis,node.js,nosql,github",
    total_experience: 0,
    file_path: "",
  },
  {
    id: 26,
    name: "RAJESH K",
    phone_numbers: "",
    email: "",
    location: "",
    region: "",
    linkedin: "",
    skills:
      "python,docker,java,graphql,sql,css,js,kubernetes,agile methodologies,typescript,aws,oracle,git,xml,scrum,html,agile,ui design,jenkins,jira,figma,terraform,rabbitmq,redis,node.js,nosql,github",
    total_experience: 0,
    file_path: "",
  },
  {
    id: 27,
    name: "RAJESH K",
    phone_numbers: "",
    email: "",
    location: "",
    region: "",
    linkedin: "",
    skills:
      "python,docker,java,graphql,sql,css,js,kubernetes,agile methodologies,typescript,aws,oracle,git,xml,scrum,html,agile,ui design,jenkins,jira,figma,terraform,rabbitmq,redis,node.js,nosql,github",
    total_experience: 0,
    file_path: "",
  },
  {
    id: 28,
    name: "RAJESH K",
    phone_numbers: "",
    email: "",
    location: "",
    region: "",
    linkedin: "",
    skills:
      "python,docker,java,graphql,sql,css,js,kubernetes,agile methodologies,typescript,aws,oracle,git,xml,scrum,html,agile,ui design,jenkins,jira,figma,terraform,rabbitmq,redis,node.js,nosql,github",
    total_experience: 0,
    file_path: "",
  },
  {
    id: 29,
    name: "RAJESH K",
    phone_numbers: "",
    email: "",
    location: "",
    region: "",
    linkedin: "",
    skills:
      "python,docker,java,graphql,sql,css,js,kubernetes,agile methodologies,typescript,aws,oracle,git,xml,scrum,html,agile,ui design,jenkins,jira,figma,terraform,rabbitmq,redis,node.js,nosql,github",
    total_experience: 0,
    file_path: "",
  },
  {
    id: 30,
    name: "RAJESH K",
    phone_numbers: "",
    email: "",
    location: "",
    region: "",
    linkedin: "",
    skills:
      "python,docker,java,graphql,sql,css,js,kubernetes,agile methodologies,typescript,aws,oracle,git,xml,scrum,html,agile,ui design,jenkins,jira,figma,terraform,rabbitmq,redis,node.js,nosql,github",
    total_experience: 0,
    file_path: "",
  },
  {
    id: 31,
    name: "RAJESH K",
    phone_numbers: "",
    email: "",
    location: "",
    region: "",
    linkedin: "",
    skills:
      "python,docker,java,graphql,sql,css,js,kubernetes,agile methodologies,typescript,aws,oracle,git,xml,scrum,html,agile,ui design,jenkins,jira,figma,terraform,rabbitmq,redis,node.js,nosql,github",
    total_experience: 0,
    file_path: "",
  },
  {
    id: 32,
    name: "RAJESH K",
    phone_numbers: "",
    email: "",
    location: "",
    region: "",
    linkedin: "",
    skills:
      "python,docker,java,graphql,sql,css,js,kubernetes,agile methodologies,typescript,aws,oracle,git,xml,scrum,html,agile,ui design,jenkins,jira,figma,terraform,rabbitmq,redis,node.js,nosql,github",
    total_experience: 0,
    file_path: "",
  },
  {
    id: 33,
    name: "RAJESH K",
    phone_numbers: "",
    email: "",
    location: "",
    region: "",
    linkedin: "",
    skills:
      "python,docker,java,graphql,sql,css,js,kubernetes,agile methodologies,typescript,aws,oracle,git,xml,scrum,html,agile,ui design,jenkins,jira,figma,terraform,rabbitmq,redis,node.js,nosql,github",
    total_experience: 0,
    file_path: "",
  },
  {
    id: 34,
    name: "RAJESH K",
    phone_numbers: "",
    email: "",
    location: "",
    region: "",
    linkedin: "",
    skills:
      "python,docker,java,graphql,sql,css,js,kubernetes,agile methodologies,typescript,aws,oracle,git,xml,scrum,html,agile,ui design,jenkins,jira,figma,terraform,rabbitmq,redis,node.js,nosql,github",
    total_experience: 0,
    file_path: "",
  },
  {
    id: 35,
    name: "RAJESH K",
    phone_numbers: "",
    email: "",
    location: "",
    region: "",
    linkedin: "",
    skills:
      "python,docker,java,graphql,sql,css,js,kubernetes,agile methodologies,typescript,aws,oracle,git,xml,scrum,html,agile,ui design,jenkins,jira,figma,terraform,rabbitmq,redis,node.js,nosql,github",
    total_experience: 0,
    file_path: "",
  },
  {
    id: 36,
    name: "RAJESH K",
    phone_numbers: "",
    email: "",
    location: "",
    region: "",
    linkedin: "",
    skills:
      "python,docker,java,graphql,sql,css,js,kubernetes,agile methodologies,typescript,aws,oracle,git,xml,scrum,html,agile,ui design,jenkins,jira,figma,terraform,rabbitmq,redis,node.js,nosql,github",
    total_experience: 0,
    file_path: "",
  },
  {
    id: 37,
    name: "Triveni Remany",
    phone_numbers: "425 394 9555",
    email: "",
    location: "",
    region: "",
    linkedin: "www.linkedin.com/in/triveni-remany",
    skills: "waterfall,xml,agile,adobe",
    total_experience: 6,
    file_path: "",
  },
  {
    id: 38,
    name: "Uday Kumar",
    phone_numbers: "",
    email: "",
    location: "",
    region: "",
    linkedin: "",
    skills:
      "agile,python,aws,java,jenkins,azure,penetration testing,c,compliance,devops,sql,css,xml,terraform,html",
    total_experience: 10,
    file_path: "",
  },
  {
    id: 39,
    name: "Uday Kumar",
    phone_numbers: "",
    email: "",
    location: "",
    region: "",
    linkedin: "",
    skills:
      "agile,python,aws,java,jenkins,azure,penetration testing,c,compliance,devops,sql,css,xml,terraform,html",
    total_experience: 10,
    file_path: "",
  },
  {
    id: 40,
    name: "Uday Kumar",
    phone_numbers: "",
    email: "",
    location: "",
    region: "",
    linkedin: "",
    skills:
      "agile,python,aws,java,jenkins,azure,penetration testing,c,compliance,devops,sql,css,xml,terraform,html",
    total_experience: 10,
    file_path: "",
  },
];
